Frontend/Backend Implementation + Unit Tests for Coffee Roaster Scenario
KSilkThread/carbonedge pull request #24
Opened 2024-03-04 17:47 UTC by AkademischDannenberg

This PR contains the full implementation including unit tests and storybook stories. Currently full functionality cannot be guaranteed as the blockchain environment is not working under minifabric on my environment. Unit Tests run successfully and stories render correctly tho.

2024-03-04 20:56 UTC, KSilkThread commented
Please add node_modules to gitignore and avoid to check-in installation artifacts.

2024-03-04 22:20 UTC, AkademischDannenberg commented
node_modules was already in .gitignore, commited with cleared cache again, now it is removed

2024-03-05 19:44 UTC, KSilkThread commented
Looks better now. One final remark: Could you please add a README file with instructions to stand-up storybook, performing unit tests, and run the test system for the webapp (frontend & backend)? That would help Sven and me to integrate it in our CI/CD pipeline later.

2024-04-05 19:28 UTC, KSilkThread requested changes
Minor remarks, most of them can be fixed by adding the final figures from the final version of the thesis.

2024-04-05 19:28 UTC, KSilkThread commented on pictures/DataModel.svg
updated version from final thesis should be placed here; instead of just the framework name, the components should be named e.g., frontend (React), backend (node-RED) etc.

2024-04-05 19:28 UTC, KSilkThread commented on scenarios/biogas-metering-horizontal/.config.runtime.json
Was storing of the secret really intentionally?

2024-04-05 19:28 UTC, KSilkThread commented on scenarios/coffee-roaster-MRV-ecosystem/docs/DataModel.png
Updated version of the figure from the final thesis should be placed here.

2024-04-28 15:42 UTC, KSilkThread submitted a review, later dismissed

2024-04-28 16:03 UTC, KSilkThread reviewed
We going to add more material soon.

2024-04-28 16:04 UTC, KSilkThread approved these changes
approved

2024-04-28 16:05 UTC, merged